=== Genbuchan/covid19-scraping/schema/main_summary.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/Main",
    "type": "object",
    "title": "The Root Schema",
    "definitions": {
        "Main": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "attr": {"type": "string"},
                "value": {"type": "integer", "default": 0},
                "children": {
                    "type": "array",
                    "items": {"$ref": "#/definitions/Inspections"}
                },
                "last_update": {
                    "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}[+][0-9]{2}:[0-9]{2}$",
                    "type": "string"
                }
            },
            "required": ["attr", "children", "last_update", "value"],
            "title": "The Main Schema"
        },
        "Inspections": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "attr": {"type": "string"},
                "value": {"type": "integer", "default": 0},
                "children": {
                    "type": "array",
                    "items": {"$ref": "#/definitions/Patients"}
                }
            },
            "required": ["attr", "children", "value"],
            "title": "The Inspections Schema"
        },
        "Patients": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "attr": {"type": "string"},
                "value": {"type": "integer", "default": 0},
                "children": {
                    "type": "array",
                    "items": {"$ref": "#/definitions/Symptoms"}
                }
            },
            "required": ["attr", "value"],
            "title": "The Patients Schema"
        },
        "Symptoms": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "attr": {"type": "string"},
                "value": {"type": "integer", "default": 0}
            },
            "required": ["attr", "value"],
            "title": "The Symptoms Schema"
        }
    }
}

=== Genbuchan/covid19-scraping/main_summary.json
{
    "attr": "検査実施人数",
    "value": 72133,
    "children": [
        {
            "attr": "陽性患者数",
            "value": 3455,
            "children": [
                {
                    "attr": "入院中",
                    "value": 211,
                    "children": [
                        {
                            "attr": "軽症・中等症",
                            "value": 197
                        },
                        {
                            "attr": "重症",
                            "value": 14
                        }
                    ]
                },
                {
                    "attr": "宿泊療養",
                    "value": 34
                },
                {
                    "attr": "死亡",
                    "value": 67
                },
                {
                    "attr": "退院",
                    "value": 3143
                }
            ]
        }
    ],
    "last_update": "2020-11-07T00:00:00+09:00"
}
